# Makefile  

# Constants:
CC=gcc
CFLAGS=-I

# Commands:
all: 
	$(CC) Exercise1.c Exercise2.c Exercise3.c -o exercises
one:
	$(CC) Exercise1.c -o exercise1
two:
	$(CC) Exercise2.c -o exercise2
three:
	$(CC) Exercise3.c -o exercise3
clean: 
	$(RM) *.o exercise1 exercise2 exercise3
